### ISSUE TITLE
Number truncation

### ISSUE THREAD

**Issue by hdgarrood** [philopon/haskell-purescript-binding#1]
Looking at this: https://github.com/philopon/haskell-purescript-binding/blob/master/Language/PureScript/Binding/Class.hs#L37

It seems like this line specifies that Integer values in Haskell should be mapped to Number values in PureScript? This is potentially quite dangerous; `Number` values can only be up to around 2^53 ish before they stop 'working' (eg: `x + 1 /= x` stops being true), so a very large `Integer` in Haskell could cause problems if it were serialised and given to a PureScript application. Additionally, what happens when trying to turn a PureScript `Number` into a Haskell `Integer` if the number is non-integral?

**Comment by philopon** [comment]
Thanks for your comment:smile:

> precision

That's right. but, not only `Integer` but `Int`(on 64bit system), `Int64`, `Word64` is unsafe. I think it's little inconvenience if I don't provide `toPureScriptType` to these.

> sign

Hmm... I implemented JSON to PureScript only. but, I think It will not throw anything in client side(and user should validate).

and, this project is very old and prototype. so, I want to rewrite it in future.
